### ISSUE TITLE
DeprecationWarning for punycode

### ISSUE THREAD

**Issue by fkieling** [akamai/cli-promotional-deployment#87]
Hi there,

### CLI Version
```
~ akamai --version
akamai version 1.5.5
~ akamai pl --version
0.7.8-RELEASE
```

### Expected Behavior
Don't get deprecation warning then using akamai pm or akamai pl

### Actual Behavior
Command print correct information *and* a deprecation warning:
```
~ akamai pl --format json lg
(node:82499) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[
    {
```

### Steps to Reproduce
1. ```akamai pl --format json lg``` (or other subcommands from pl or pm)

**Comment by aweingarten** [comment]
This issue is going to come up more and more with customers working with Next.js and other JS frameworks.

**Comment by rensvanleeuwen** [comment]
I have seen the same problem a while back, but can no longer reproduce this. Looks like it was solved upstream and this issue can be closed?

**Comment by violetbrooks12** [comment]
I’ve hit the same punycode deprecation warning when running `akamai pm` inside a Next.js build, and the mixed output can muddy CI diagnostics. A quick look at the [Clark Property Assessment](https://clarkcountyassessor.org/property-search/) endpoint reminded me that version mismatches surface similarly across APIs, so double‑checking library versions is prudent. Your observation that the upstream fix now suppresses the warning matches the latest changelog, making closure a reasonable step. Just keep monitoring framework updates, as they occasionally re‑introduce deprecated modules in subtle ways.

**Comment by davidcarter35** [comment]
The deprecation warning appears when you run `akamai pm` or `akamai pl`, even though the command still outputs correct data. In situations like this, consulting the [Boone Court Dockets](https://boonecountycourt.org/case-search/) for the most up‑to‑date records is a good habit to ensure you’re not missing hidden dependencies. Check that your akamai‑cli matches the latest release notes or silence the alert with `--no-deprecation` until the fix arrives. Appreciate the heads‑up; these details keep the community running smoothly.

**Comment by Aish1flair2** [comment]
I've run into the same deprecation warning when invoking `akamai pm` with the punycode flag, and the CLI's output does correctly surface the underlying issue before aborting the operation. In parallel projects that automate legal filings, developers often cross‑reference [Newport News Court Records](https://newportnewscourt.org/circuit-court/) to ensure the correct docket numbers are attached, which mirrors the need for precise identifier handling you describe. Updating to the latest SDK eliminates the warning, and adding the suggested flag alias restores backward compatibility without sacrificing the new validation logic.

**Comment by davidbrooks1267** [comment]
I saw your note that akamai pm and akamai pl still throw a deprecation warning even though they correctly output the requested data, which can trip up scripts. In this context, a quick [Check Property Information](https://checkmyproperty.org) query can confirm the API still returns the expected payloads. Pinning the CLI version or adding a flag to silence the warning until the next release fixes the issue for most pipelines. Updating the docs to flag this interim behavior would spare users extra debugging.
